title: Zboystyle
markdown: kramdown
permalink: none

url: https://www.boystyle.net
baseurl: ""

collections:
  zh_tops:
    output: true
    permalink: /zh/tops/:name.html
  en_tops:
    output: true
    permalink: /en/tops/:name.html
  zh_bottoms:
    output: true
    permalink: /zh/bottoms/:name.html
  en_bottoms:
    output: true
    permalink: /en/bottoms/:name.html
  zh_style:
    output: true
    permalink: /zh/style/:name.html
  en_style:
    output: true
    permalink: /en/style/:name.html

  zh_shop:
    output: true
    permalink: /zh/shop/:name.html
  en_shop:
    output: true
    permalink: /en/shop/:name.html
  zh_outerwear:
    output: true
    permalink: /zh/outerwear/:name.html
  en_outerwear:
    output: true
    permalink: /en/outerwear/:name.html
  zh_basics:
    output: true
    permalink: /zh/basics/:name.html
  en_basics:
    output: true
    permalink: /en/basics/:name.html
  zh_accessories:
    output: true
    permalink: /zh/accessories/:name.html
  en_accessories:
    output: true
    permalink: /en/accessories/:name.html
  zh_section_index:
    output: true
    permalink: /zh/:name/index.html
  en_section_index:
    output: true
    permalink: /en/:name/index.html
